version: "3.9"
services:
  face_recognition:
    build: ./face-recognition
    dns:
      - 8.8.8.8
    volumes:
      - ./stream:/home/stream
      - ./face-recognition:/home/face-recognition
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    
  object_detector:
    build: ./object-detector
    dns:
      - 8.8.8.8
    volumes:
      - ./stream:/home/stream
      - ./object-detector:/home/object-detector
      - /home/object-detector/lib/
      - ./resources:/home/object-detector/resources
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  
  object_tracking:
    build: ./object-tracking
    dns:
      - 8.8.8.8
    volumes:
      - ./stream:/home/stream
      - ./object-tracking:/home/object-tracking
      - ./resources:/home/object-tracking/resources
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  ocr_analysis:
    build: ./ocr-analysis
    dns:
      - 8.8.8.8
    volumes:
      - ./stream:/home/stream
      - ./ocr-analysis:/home/ocr-analysis
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  pose_estimation:
    build: ./pose-estimation
    dns:
      - 8.8.8.8
    volumes:
      - ./stream:/home/stream
      - ./pose-estimation:/home/pose-estimation
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  
  stream:
    build: ./stream
    volumes:
      - ./stream:/home/stream
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - "/dev/video0:/dev/video0"